# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(457, 529)
        Dialog.setStyleSheet("file:///C:/Users/Admin/Desktop/front.jfif")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 70, 431, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.textinput = QtWidgets.QTextEdit(Dialog)
        self.textinput.setGeometry(QtCore.QRect(10, 450, 361, 31))
        self.textinput.setObjectName("textinput")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(370, 450, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.nameinput = QtWidgets.QLineEdit(Dialog)
        self.nameinput.setGeometry(QtCore.QRect(330, 30, 113, 22))
        self.nameinput.setObjectName("nameinput")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 33, 61, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Messenger for Pachnof"))
        self.label.setText(_translate("Dialog", "Messenger for Pachnof"))
        self.textinput.setPlaceholderText(_translate("Dialog", "Введите текст..."))
        self.pushButton.setText(_translate("Dialog", "отправить"))
        self.nameinput.setPlaceholderText(_translate("Dialog", "Slavka..."))
        self.label_2.setText(_translate("Dialog", "Nickname:"))
